 export default {
   DATA_GRIDSTRAP : 'gridstrap',
   DATA_HIDDEN_CELL : 'gridstrap-hidden-cell',
   DATA_VISIBLE_CELL : 'gridstrap-visible-cell', 
   DATA_MOUSEDOWN_POSITION_DIFF : 'gridstrap-mousedown-position-diff',
   DATA_MOUSEDOWN_SIZE : 'gridstrap-mousedown-size',
   DATA_CELL_POSITION_AND_SIZE : 'gridstrap-position-size',
   EVENT_DRAGSTART : 'dragstart',
   EVENT_MOUSEDOWN : 'mousedown',
   EVENT_MOUSEOVER : 'mouseover',
   EVENT_MOUSEMOVE : 'mousemove',
   EVENT_MOUSEUP : 'mouseup',
   EVENT_TOUCHSTART: 'touchstart',
   EVENT_TOUCHMOVE: 'touchmove', 
   EVENT_TOUCHEND: 'touchend',
   EVENT_RESIZE : 'resize',
   EVENT_CELL_RESIZE : 'cellresize',
   EVENT_CELL_DRAG: 'celldrag',
   EVENT_CELL_REDRAW: 'cellredraw',
   ERROR_MISSING_JQUERY: 'Requires jQuery v3.2.1', 
   ERROR_INVALID_ATTACH_ELEMENT : 'Cannot attach element that is not a child of gridstrap parent.',
   ERROR_NONCONTIGUOUS_HTML_UNDEFINED : 'nonContiguousCellHtml option cannot be null.'
};
